apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
  labels: 
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image:  bokjo/frontend-k8s-demo:latest
          imagePullPolicy: Always
          ports:
          - name:  frontend-svc
            containerPort: 3000